name: Build Deploy
run-name: Building and Deploying app for ${{github.actor}} 🚀
on:
  push:
    branches:
      - 'master'
      - 'github_actions'
jobs:
  BuildAndPushImage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload Test Runner
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build And Push Docker Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/carflow-backend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/carflow-backend:${{ github.sha }}
  DeployContainerApp:
    runs-on: ubuntu-latest
    needs: BuildAndPushImage
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v0
        with:
          acrName: ${{ secrets.REGISTRY_NAME }}
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/carflow-backend:${{ github.sha }}
          containerAppName: carflow-backend
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          containerAppEnvironment: managedEnvironment-playground-ba45
          environmentVariables: SPRING_DATASOURCE_PASSWORD=secretref:dbpass SPRING_DATASOURCE_USERNAME=secretref:dbuser SPRING_DATASOURCE_URL=secretref:dburl
          location: West Europe
          ingress: external
          targetPort: 8080